
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Team
 * 
 */
export type Team = Prisma.TeamModel
/**
 * Model Client
 * 
 */
export type Client = Prisma.ClientModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model Material
 * 
 */
export type Material = Prisma.MaterialModel
/**
 * Model InventoryItem
 * 
 */
export type InventoryItem = Prisma.InventoryItemModel
/**
 * Model InventoryMovement
 * 
 */
export type InventoryMovement = Prisma.InventoryMovementModel
/**
 * Model ProjectTeamAssignment
 * 
 */
export type ProjectTeamAssignment = Prisma.ProjectTeamAssignmentModel
/**
 * Model WorkHours
 * 
 */
export type WorkHours = Prisma.WorkHoursModel
/**
 * Model MaterialsInProject
 * 
 */
export type MaterialsInProject = Prisma.MaterialsInProjectModel
