
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProjectTeamAssignment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProjectTeamAssignment
 * 
 */
export type ProjectTeamAssignmentModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectTeamAssignmentPayload>

export type AggregateProjectTeamAssignment = {
  _count: ProjectTeamAssignmentCountAggregateOutputType | null
  _min: ProjectTeamAssignmentMinAggregateOutputType | null
  _max: ProjectTeamAssignmentMaxAggregateOutputType | null
}

export type ProjectTeamAssignmentMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  teamId: string | null
  role: string | null
  assignedDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectTeamAssignmentMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  teamId: string | null
  role: string | null
  assignedDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectTeamAssignmentCountAggregateOutputType = {
  id: number
  projectId: number
  teamId: number
  role: number
  assignedDate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProjectTeamAssignmentMinAggregateInputType = {
  id?: true
  projectId?: true
  teamId?: true
  role?: true
  assignedDate?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectTeamAssignmentMaxAggregateInputType = {
  id?: true
  projectId?: true
  teamId?: true
  role?: true
  assignedDate?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectTeamAssignmentCountAggregateInputType = {
  id?: true
  projectId?: true
  teamId?: true
  role?: true
  assignedDate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProjectTeamAssignmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectTeamAssignment to aggregate.
   */
  where?: Prisma.ProjectTeamAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTeamAssignments to fetch.
   */
  orderBy?: Prisma.ProjectTeamAssignmentOrderByWithRelationInput | Prisma.ProjectTeamAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectTeamAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTeamAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTeamAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProjectTeamAssignments
  **/
  _count?: true | ProjectTeamAssignmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectTeamAssignmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectTeamAssignmentMaxAggregateInputType
}

export type GetProjectTeamAssignmentAggregateType<T extends ProjectTeamAssignmentAggregateArgs> = {
      [P in keyof T & keyof AggregateProjectTeamAssignment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProjectTeamAssignment[P]>
    : Prisma.GetScalarType<T[P], AggregateProjectTeamAssignment[P]>
}




export type ProjectTeamAssignmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectTeamAssignmentWhereInput
  orderBy?: Prisma.ProjectTeamAssignmentOrderByWithAggregationInput | Prisma.ProjectTeamAssignmentOrderByWithAggregationInput[]
  by: Prisma.ProjectTeamAssignmentScalarFieldEnum[] | Prisma.ProjectTeamAssignmentScalarFieldEnum
  having?: Prisma.ProjectTeamAssignmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectTeamAssignmentCountAggregateInputType | true
  _min?: ProjectTeamAssignmentMinAggregateInputType
  _max?: ProjectTeamAssignmentMaxAggregateInputType
}

export type ProjectTeamAssignmentGroupByOutputType = {
  id: string
  projectId: string
  teamId: string
  role: string | null
  assignedDate: Date
  createdAt: Date
  updatedAt: Date
  _count: ProjectTeamAssignmentCountAggregateOutputType | null
  _min: ProjectTeamAssignmentMinAggregateOutputType | null
  _max: ProjectTeamAssignmentMaxAggregateOutputType | null
}

export type GetProjectTeamAssignmentGroupByPayload<T extends ProjectTeamAssignmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectTeamAssignmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectTeamAssignmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectTeamAssignmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectTeamAssignmentGroupByOutputType[P]>
      }
    >
  >



export type ProjectTeamAssignmentWhereInput = {
  AND?: Prisma.ProjectTeamAssignmentWhereInput | Prisma.ProjectTeamAssignmentWhereInput[]
  OR?: Prisma.ProjectTeamAssignmentWhereInput[]
  NOT?: Prisma.ProjectTeamAssignmentWhereInput | Prisma.ProjectTeamAssignmentWhereInput[]
  id?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  projectId?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  teamId?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  role?: Prisma.StringNullableFilter<"ProjectTeamAssignment"> | string | null
  assignedDate?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}

export type ProjectTeamAssignmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  assignedDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  team?: Prisma.TeamOrderByWithRelationInput
}

export type ProjectTeamAssignmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  projectId_teamId?: Prisma.ProjectTeamAssignmentProjectIdTeamIdCompoundUniqueInput
  AND?: Prisma.ProjectTeamAssignmentWhereInput | Prisma.ProjectTeamAssignmentWhereInput[]
  OR?: Prisma.ProjectTeamAssignmentWhereInput[]
  NOT?: Prisma.ProjectTeamAssignmentWhereInput | Prisma.ProjectTeamAssignmentWhereInput[]
  projectId?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  teamId?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  role?: Prisma.StringNullableFilter<"ProjectTeamAssignment"> | string | null
  assignedDate?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}, "id" | "projectId_teamId">

export type ProjectTeamAssignmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  assignedDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProjectTeamAssignmentCountOrderByAggregateInput
  _max?: Prisma.ProjectTeamAssignmentMaxOrderByAggregateInput
  _min?: Prisma.ProjectTeamAssignmentMinOrderByAggregateInput
}

export type ProjectTeamAssignmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectTeamAssignmentScalarWhereWithAggregatesInput | Prisma.ProjectTeamAssignmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectTeamAssignmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectTeamAssignmentScalarWhereWithAggregatesInput | Prisma.ProjectTeamAssignmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProjectTeamAssignment"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"ProjectTeamAssignment"> | string
  teamId?: Prisma.StringWithAggregatesFilter<"ProjectTeamAssignment"> | string
  role?: Prisma.StringNullableWithAggregatesFilter<"ProjectTeamAssignment"> | string | null
  assignedDate?: Prisma.DateTimeWithAggregatesFilter<"ProjectTeamAssignment"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProjectTeamAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ProjectTeamAssignment"> | Date | string
}

export type ProjectTeamAssignmentCreateInput = {
  id?: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutTeamAssignmentsInput
  team: Prisma.TeamCreateNestedOneWithoutProjectAssignmentsInput
}

export type ProjectTeamAssignmentUncheckedCreateInput = {
  id?: string
  projectId: string
  teamId: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectTeamAssignmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutTeamAssignmentsNestedInput
  team?: Prisma.TeamUpdateOneRequiredWithoutProjectAssignmentsNestedInput
}

export type ProjectTeamAssignmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectTeamAssignmentCreateManyInput = {
  id?: string
  projectId: string
  teamId: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectTeamAssignmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectTeamAssignmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectTeamAssignmentListRelationFilter = {
  every?: Prisma.ProjectTeamAssignmentWhereInput
  some?: Prisma.ProjectTeamAssignmentWhereInput
  none?: Prisma.ProjectTeamAssignmentWhereInput
}

export type ProjectTeamAssignmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjectTeamAssignmentProjectIdTeamIdCompoundUniqueInput = {
  projectId: string
  teamId: string
}

export type ProjectTeamAssignmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  assignedDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectTeamAssignmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  assignedDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectTeamAssignmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  assignedDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectTeamAssignmentCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput> | Prisma.ProjectTeamAssignmentCreateWithoutTeamInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyTeamInputEnvelope
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
}

export type ProjectTeamAssignmentUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput> | Prisma.ProjectTeamAssignmentCreateWithoutTeamInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyTeamInputEnvelope
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
}

export type ProjectTeamAssignmentUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput> | Prisma.ProjectTeamAssignmentCreateWithoutTeamInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutTeamInput | Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyTeamInputEnvelope
  set?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  disconnect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  delete?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  update?: Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutTeamInput | Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutTeamInput | Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.ProjectTeamAssignmentScalarWhereInput | Prisma.ProjectTeamAssignmentScalarWhereInput[]
}

export type ProjectTeamAssignmentUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput> | Prisma.ProjectTeamAssignmentCreateWithoutTeamInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutTeamInput | Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyTeamInputEnvelope
  set?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  disconnect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  delete?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  update?: Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutTeamInput | Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutTeamInput | Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.ProjectTeamAssignmentScalarWhereInput | Prisma.ProjectTeamAssignmentScalarWhereInput[]
}

export type ProjectTeamAssignmentCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput> | Prisma.ProjectTeamAssignmentCreateWithoutProjectInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
}

export type ProjectTeamAssignmentUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput> | Prisma.ProjectTeamAssignmentCreateWithoutProjectInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyProjectInputEnvelope
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
}

export type ProjectTeamAssignmentUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput> | Prisma.ProjectTeamAssignmentCreateWithoutProjectInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyProjectInputEnvelope
  set?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  disconnect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  delete?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  update?: Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectTeamAssignmentScalarWhereInput | Prisma.ProjectTeamAssignmentScalarWhereInput[]
}

export type ProjectTeamAssignmentUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput> | Prisma.ProjectTeamAssignmentCreateWithoutProjectInput[] | Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput | Prisma.ProjectTeamAssignmentCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutProjectInput | Prisma.ProjectTeamAssignmentUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ProjectTeamAssignmentCreateManyProjectInputEnvelope
  set?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  disconnect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  delete?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  connect?: Prisma.ProjectTeamAssignmentWhereUniqueInput | Prisma.ProjectTeamAssignmentWhereUniqueInput[]
  update?: Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutProjectInput | Prisma.ProjectTeamAssignmentUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutProjectInput | Prisma.ProjectTeamAssignmentUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ProjectTeamAssignmentScalarWhereInput | Prisma.ProjectTeamAssignmentScalarWhereInput[]
}

export type ProjectTeamAssignmentCreateWithoutTeamInput = {
  id?: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutTeamAssignmentsInput
}

export type ProjectTeamAssignmentUncheckedCreateWithoutTeamInput = {
  id?: string
  projectId: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectTeamAssignmentCreateOrConnectWithoutTeamInput = {
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput>
}

export type ProjectTeamAssignmentCreateManyTeamInputEnvelope = {
  data: Prisma.ProjectTeamAssignmentCreateManyTeamInput | Prisma.ProjectTeamAssignmentCreateManyTeamInput[]
}

export type ProjectTeamAssignmentUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutTeamInput>
}

export type ProjectTeamAssignmentUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateWithoutTeamInput, Prisma.ProjectTeamAssignmentUncheckedUpdateWithoutTeamInput>
}

export type ProjectTeamAssignmentUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.ProjectTeamAssignmentScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateManyMutationInput, Prisma.ProjectTeamAssignmentUncheckedUpdateManyWithoutTeamInput>
}

export type ProjectTeamAssignmentScalarWhereInput = {
  AND?: Prisma.ProjectTeamAssignmentScalarWhereInput | Prisma.ProjectTeamAssignmentScalarWhereInput[]
  OR?: Prisma.ProjectTeamAssignmentScalarWhereInput[]
  NOT?: Prisma.ProjectTeamAssignmentScalarWhereInput | Prisma.ProjectTeamAssignmentScalarWhereInput[]
  id?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  projectId?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  teamId?: Prisma.StringFilter<"ProjectTeamAssignment"> | string
  role?: Prisma.StringNullableFilter<"ProjectTeamAssignment"> | string | null
  assignedDate?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProjectTeamAssignment"> | Date | string
}

export type ProjectTeamAssignmentCreateWithoutProjectInput = {
  id?: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  team: Prisma.TeamCreateNestedOneWithoutProjectAssignmentsInput
}

export type ProjectTeamAssignmentUncheckedCreateWithoutProjectInput = {
  id?: string
  teamId: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectTeamAssignmentCreateOrConnectWithoutProjectInput = {
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput>
}

export type ProjectTeamAssignmentCreateManyProjectInputEnvelope = {
  data: Prisma.ProjectTeamAssignmentCreateManyProjectInput | Prisma.ProjectTeamAssignmentCreateManyProjectInput[]
}

export type ProjectTeamAssignmentUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedCreateWithoutProjectInput>
}

export type ProjectTeamAssignmentUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateWithoutProjectInput, Prisma.ProjectTeamAssignmentUncheckedUpdateWithoutProjectInput>
}

export type ProjectTeamAssignmentUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ProjectTeamAssignmentScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateManyMutationInput, Prisma.ProjectTeamAssignmentUncheckedUpdateManyWithoutProjectInput>
}

export type ProjectTeamAssignmentCreateManyTeamInput = {
  id?: string
  projectId: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectTeamAssignmentUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutTeamAssignmentsNestedInput
}

export type ProjectTeamAssignmentUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectTeamAssignmentUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectTeamAssignmentCreateManyProjectInput = {
  id?: string
  teamId: string
  role?: string | null
  assignedDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectTeamAssignmentUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  team?: Prisma.TeamUpdateOneRequiredWithoutProjectAssignmentsNestedInput
}

export type ProjectTeamAssignmentUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectTeamAssignmentUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProjectTeamAssignmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  teamId?: boolean
  role?: boolean
  assignedDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectTeamAssignment"]>

export type ProjectTeamAssignmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  teamId?: boolean
  role?: boolean
  assignedDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectTeamAssignment"]>

export type ProjectTeamAssignmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  teamId?: boolean
  role?: boolean
  assignedDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["projectTeamAssignment"]>

export type ProjectTeamAssignmentSelectScalar = {
  id?: boolean
  projectId?: boolean
  teamId?: boolean
  role?: boolean
  assignedDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProjectTeamAssignmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "teamId" | "role" | "assignedDate" | "createdAt" | "updatedAt", ExtArgs["result"]["projectTeamAssignment"]>
export type ProjectTeamAssignmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type ProjectTeamAssignmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type ProjectTeamAssignmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}

export type $ProjectTeamAssignmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProjectTeamAssignment"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    team: Prisma.$TeamPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    teamId: string
    role: string | null
    assignedDate: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["projectTeamAssignment"]>
  composites: {}
}

export type ProjectTeamAssignmentGetPayload<S extends boolean | null | undefined | ProjectTeamAssignmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload, S>

export type ProjectTeamAssignmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectTeamAssignmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectTeamAssignmentCountAggregateInputType | true
  }

export interface ProjectTeamAssignmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProjectTeamAssignment'], meta: { name: 'ProjectTeamAssignment' } }
  /**
   * Find zero or one ProjectTeamAssignment that matches the filter.
   * @param {ProjectTeamAssignmentFindUniqueArgs} args - Arguments to find a ProjectTeamAssignment
   * @example
   * // Get one ProjectTeamAssignment
   * const projectTeamAssignment = await prisma.projectTeamAssignment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectTeamAssignmentFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProjectTeamAssignment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectTeamAssignmentFindUniqueOrThrowArgs} args - Arguments to find a ProjectTeamAssignment
   * @example
   * // Get one ProjectTeamAssignment
   * const projectTeamAssignment = await prisma.projectTeamAssignment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectTeamAssignmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectTeamAssignment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTeamAssignmentFindFirstArgs} args - Arguments to find a ProjectTeamAssignment
   * @example
   * // Get one ProjectTeamAssignment
   * const projectTeamAssignment = await prisma.projectTeamAssignment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectTeamAssignmentFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectTeamAssignmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProjectTeamAssignment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTeamAssignmentFindFirstOrThrowArgs} args - Arguments to find a ProjectTeamAssignment
   * @example
   * // Get one ProjectTeamAssignment
   * const projectTeamAssignment = await prisma.projectTeamAssignment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectTeamAssignmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectTeamAssignmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProjectTeamAssignments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTeamAssignmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProjectTeamAssignments
   * const projectTeamAssignments = await prisma.projectTeamAssignment.findMany()
   * 
   * // Get first 10 ProjectTeamAssignments
   * const projectTeamAssignments = await prisma.projectTeamAssignment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectTeamAssignmentWithIdOnly = await prisma.projectTeamAssignment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectTeamAssignmentFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectTeamAssignmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProjectTeamAssignment.
   * @param {ProjectTeamAssignmentCreateArgs} args - Arguments to create a ProjectTeamAssignment.
   * @example
   * // Create one ProjectTeamAssignment
   * const ProjectTeamAssignment = await prisma.projectTeamAssignment.create({
   *   data: {
   *     // ... data to create a ProjectTeamAssignment
   *   }
   * })
   * 
   */
  create<T extends ProjectTeamAssignmentCreateArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProjectTeamAssignments.
   * @param {ProjectTeamAssignmentCreateManyArgs} args - Arguments to create many ProjectTeamAssignments.
   * @example
   * // Create many ProjectTeamAssignments
   * const projectTeamAssignment = await prisma.projectTeamAssignment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectTeamAssignmentCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectTeamAssignmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProjectTeamAssignments and returns the data saved in the database.
   * @param {ProjectTeamAssignmentCreateManyAndReturnArgs} args - Arguments to create many ProjectTeamAssignments.
   * @example
   * // Create many ProjectTeamAssignments
   * const projectTeamAssignment = await prisma.projectTeamAssignment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProjectTeamAssignments and only return the `id`
   * const projectTeamAssignmentWithIdOnly = await prisma.projectTeamAssignment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectTeamAssignmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectTeamAssignmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProjectTeamAssignment.
   * @param {ProjectTeamAssignmentDeleteArgs} args - Arguments to delete one ProjectTeamAssignment.
   * @example
   * // Delete one ProjectTeamAssignment
   * const ProjectTeamAssignment = await prisma.projectTeamAssignment.delete({
   *   where: {
   *     // ... filter to delete one ProjectTeamAssignment
   *   }
   * })
   * 
   */
  delete<T extends ProjectTeamAssignmentDeleteArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProjectTeamAssignment.
   * @param {ProjectTeamAssignmentUpdateArgs} args - Arguments to update one ProjectTeamAssignment.
   * @example
   * // Update one ProjectTeamAssignment
   * const projectTeamAssignment = await prisma.projectTeamAssignment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectTeamAssignmentUpdateArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProjectTeamAssignments.
   * @param {ProjectTeamAssignmentDeleteManyArgs} args - Arguments to filter ProjectTeamAssignments to delete.
   * @example
   * // Delete a few ProjectTeamAssignments
   * const { count } = await prisma.projectTeamAssignment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectTeamAssignmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectTeamAssignmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectTeamAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTeamAssignmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProjectTeamAssignments
   * const projectTeamAssignment = await prisma.projectTeamAssignment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectTeamAssignmentUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProjectTeamAssignments and returns the data updated in the database.
   * @param {ProjectTeamAssignmentUpdateManyAndReturnArgs} args - Arguments to update many ProjectTeamAssignments.
   * @example
   * // Update many ProjectTeamAssignments
   * const projectTeamAssignment = await prisma.projectTeamAssignment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProjectTeamAssignments and only return the `id`
   * const projectTeamAssignmentWithIdOnly = await prisma.projectTeamAssignment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectTeamAssignmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProjectTeamAssignment.
   * @param {ProjectTeamAssignmentUpsertArgs} args - Arguments to update or create a ProjectTeamAssignment.
   * @example
   * // Update or create a ProjectTeamAssignment
   * const projectTeamAssignment = await prisma.projectTeamAssignment.upsert({
   *   create: {
   *     // ... data to create a ProjectTeamAssignment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProjectTeamAssignment we want to update
   *   }
   * })
   */
  upsert<T extends ProjectTeamAssignmentUpsertArgs>(args: Prisma.SelectSubset<T, ProjectTeamAssignmentUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectTeamAssignmentClient<runtime.Types.Result.GetResult<Prisma.$ProjectTeamAssignmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProjectTeamAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTeamAssignmentCountArgs} args - Arguments to filter ProjectTeamAssignments to count.
   * @example
   * // Count the number of ProjectTeamAssignments
   * const count = await prisma.projectTeamAssignment.count({
   *   where: {
   *     // ... the filter for the ProjectTeamAssignments we want to count
   *   }
   * })
  **/
  count<T extends ProjectTeamAssignmentCountArgs>(
    args?: Prisma.Subset<T, ProjectTeamAssignmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectTeamAssignmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProjectTeamAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTeamAssignmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectTeamAssignmentAggregateArgs>(args: Prisma.Subset<T, ProjectTeamAssignmentAggregateArgs>): Prisma.PrismaPromise<GetProjectTeamAssignmentAggregateType<T>>

  /**
   * Group by ProjectTeamAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectTeamAssignmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectTeamAssignmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectTeamAssignmentGroupByArgs['orderBy'] }
      : { orderBy?: ProjectTeamAssignmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectTeamAssignmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectTeamAssignmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProjectTeamAssignment model
 */
readonly fields: ProjectTeamAssignmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProjectTeamAssignment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectTeamAssignmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProjectTeamAssignment model
 */
export interface ProjectTeamAssignmentFieldRefs {
  readonly id: Prisma.FieldRef<"ProjectTeamAssignment", 'String'>
  readonly projectId: Prisma.FieldRef<"ProjectTeamAssignment", 'String'>
  readonly teamId: Prisma.FieldRef<"ProjectTeamAssignment", 'String'>
  readonly role: Prisma.FieldRef<"ProjectTeamAssignment", 'String'>
  readonly assignedDate: Prisma.FieldRef<"ProjectTeamAssignment", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ProjectTeamAssignment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ProjectTeamAssignment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProjectTeamAssignment findUnique
 */
export type ProjectTeamAssignmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTeamAssignment to fetch.
   */
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
}

/**
 * ProjectTeamAssignment findUniqueOrThrow
 */
export type ProjectTeamAssignmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTeamAssignment to fetch.
   */
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
}

/**
 * ProjectTeamAssignment findFirst
 */
export type ProjectTeamAssignmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTeamAssignment to fetch.
   */
  where?: Prisma.ProjectTeamAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTeamAssignments to fetch.
   */
  orderBy?: Prisma.ProjectTeamAssignmentOrderByWithRelationInput | Prisma.ProjectTeamAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectTeamAssignments.
   */
  cursor?: Prisma.ProjectTeamAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTeamAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTeamAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectTeamAssignments.
   */
  distinct?: Prisma.ProjectTeamAssignmentScalarFieldEnum | Prisma.ProjectTeamAssignmentScalarFieldEnum[]
}

/**
 * ProjectTeamAssignment findFirstOrThrow
 */
export type ProjectTeamAssignmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTeamAssignment to fetch.
   */
  where?: Prisma.ProjectTeamAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTeamAssignments to fetch.
   */
  orderBy?: Prisma.ProjectTeamAssignmentOrderByWithRelationInput | Prisma.ProjectTeamAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProjectTeamAssignments.
   */
  cursor?: Prisma.ProjectTeamAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTeamAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTeamAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectTeamAssignments.
   */
  distinct?: Prisma.ProjectTeamAssignmentScalarFieldEnum | Prisma.ProjectTeamAssignmentScalarFieldEnum[]
}

/**
 * ProjectTeamAssignment findMany
 */
export type ProjectTeamAssignmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which ProjectTeamAssignments to fetch.
   */
  where?: Prisma.ProjectTeamAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProjectTeamAssignments to fetch.
   */
  orderBy?: Prisma.ProjectTeamAssignmentOrderByWithRelationInput | Prisma.ProjectTeamAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProjectTeamAssignments.
   */
  cursor?: Prisma.ProjectTeamAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProjectTeamAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProjectTeamAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProjectTeamAssignments.
   */
  distinct?: Prisma.ProjectTeamAssignmentScalarFieldEnum | Prisma.ProjectTeamAssignmentScalarFieldEnum[]
}

/**
 * ProjectTeamAssignment create
 */
export type ProjectTeamAssignmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * The data needed to create a ProjectTeamAssignment.
   */
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateInput, Prisma.ProjectTeamAssignmentUncheckedCreateInput>
}

/**
 * ProjectTeamAssignment createMany
 */
export type ProjectTeamAssignmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProjectTeamAssignments.
   */
  data: Prisma.ProjectTeamAssignmentCreateManyInput | Prisma.ProjectTeamAssignmentCreateManyInput[]
}

/**
 * ProjectTeamAssignment createManyAndReturn
 */
export type ProjectTeamAssignmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * The data used to create many ProjectTeamAssignments.
   */
  data: Prisma.ProjectTeamAssignmentCreateManyInput | Prisma.ProjectTeamAssignmentCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectTeamAssignment update
 */
export type ProjectTeamAssignmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * The data needed to update a ProjectTeamAssignment.
   */
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateInput, Prisma.ProjectTeamAssignmentUncheckedUpdateInput>
  /**
   * Choose, which ProjectTeamAssignment to update.
   */
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
}

/**
 * ProjectTeamAssignment updateMany
 */
export type ProjectTeamAssignmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProjectTeamAssignments.
   */
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateManyMutationInput, Prisma.ProjectTeamAssignmentUncheckedUpdateManyInput>
  /**
   * Filter which ProjectTeamAssignments to update
   */
  where?: Prisma.ProjectTeamAssignmentWhereInput
  /**
   * Limit how many ProjectTeamAssignments to update.
   */
  limit?: number
}

/**
 * ProjectTeamAssignment updateManyAndReturn
 */
export type ProjectTeamAssignmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * The data used to update ProjectTeamAssignments.
   */
  data: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateManyMutationInput, Prisma.ProjectTeamAssignmentUncheckedUpdateManyInput>
  /**
   * Filter which ProjectTeamAssignments to update
   */
  where?: Prisma.ProjectTeamAssignmentWhereInput
  /**
   * Limit how many ProjectTeamAssignments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProjectTeamAssignment upsert
 */
export type ProjectTeamAssignmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * The filter to search for the ProjectTeamAssignment to update in case it exists.
   */
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
  /**
   * In case the ProjectTeamAssignment found by the `where` argument doesn't exist, create a new ProjectTeamAssignment with this data.
   */
  create: Prisma.XOR<Prisma.ProjectTeamAssignmentCreateInput, Prisma.ProjectTeamAssignmentUncheckedCreateInput>
  /**
   * In case the ProjectTeamAssignment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectTeamAssignmentUpdateInput, Prisma.ProjectTeamAssignmentUncheckedUpdateInput>
}

/**
 * ProjectTeamAssignment delete
 */
export type ProjectTeamAssignmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
  /**
   * Filter which ProjectTeamAssignment to delete.
   */
  where: Prisma.ProjectTeamAssignmentWhereUniqueInput
}

/**
 * ProjectTeamAssignment deleteMany
 */
export type ProjectTeamAssignmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProjectTeamAssignments to delete
   */
  where?: Prisma.ProjectTeamAssignmentWhereInput
  /**
   * Limit how many ProjectTeamAssignments to delete.
   */
  limit?: number
}

/**
 * ProjectTeamAssignment without action
 */
export type ProjectTeamAssignmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectTeamAssignment
   */
  select?: Prisma.ProjectTeamAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectTeamAssignment
   */
  omit?: Prisma.ProjectTeamAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectTeamAssignmentInclude<ExtArgs> | null
}
