
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkHours` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkHours
 * 
 */
export type WorkHoursModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkHoursPayload>

export type AggregateWorkHours = {
  _count: WorkHoursCountAggregateOutputType | null
  _avg: WorkHoursAvgAggregateOutputType | null
  _sum: WorkHoursSumAggregateOutputType | null
  _min: WorkHoursMinAggregateOutputType | null
  _max: WorkHoursMaxAggregateOutputType | null
}

export type WorkHoursAvgAggregateOutputType = {
  hoursWorked: number | null
}

export type WorkHoursSumAggregateOutputType = {
  hoursWorked: number | null
}

export type WorkHoursMinAggregateOutputType = {
  id: string | null
  teamId: string | null
  projectId: string | null
  hoursWorked: number | null
  date: Date | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorkHoursMaxAggregateOutputType = {
  id: string | null
  teamId: string | null
  projectId: string | null
  hoursWorked: number | null
  date: Date | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorkHoursCountAggregateOutputType = {
  id: number
  teamId: number
  projectId: number
  hoursWorked: number
  date: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type WorkHoursAvgAggregateInputType = {
  hoursWorked?: true
}

export type WorkHoursSumAggregateInputType = {
  hoursWorked?: true
}

export type WorkHoursMinAggregateInputType = {
  id?: true
  teamId?: true
  projectId?: true
  hoursWorked?: true
  date?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type WorkHoursMaxAggregateInputType = {
  id?: true
  teamId?: true
  projectId?: true
  hoursWorked?: true
  date?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type WorkHoursCountAggregateInputType = {
  id?: true
  teamId?: true
  projectId?: true
  hoursWorked?: true
  date?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WorkHoursAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkHours to aggregate.
   */
  where?: Prisma.WorkHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkHours to fetch.
   */
  orderBy?: Prisma.WorkHoursOrderByWithRelationInput | Prisma.WorkHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkHours
  **/
  _count?: true | WorkHoursCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkHoursAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkHoursSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkHoursMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkHoursMaxAggregateInputType
}

export type GetWorkHoursAggregateType<T extends WorkHoursAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkHours]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkHours[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkHours[P]>
}




export type WorkHoursGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkHoursWhereInput
  orderBy?: Prisma.WorkHoursOrderByWithAggregationInput | Prisma.WorkHoursOrderByWithAggregationInput[]
  by: Prisma.WorkHoursScalarFieldEnum[] | Prisma.WorkHoursScalarFieldEnum
  having?: Prisma.WorkHoursScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkHoursCountAggregateInputType | true
  _avg?: WorkHoursAvgAggregateInputType
  _sum?: WorkHoursSumAggregateInputType
  _min?: WorkHoursMinAggregateInputType
  _max?: WorkHoursMaxAggregateInputType
}

export type WorkHoursGroupByOutputType = {
  id: string
  teamId: string
  projectId: string
  hoursWorked: number
  date: Date
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: WorkHoursCountAggregateOutputType | null
  _avg: WorkHoursAvgAggregateOutputType | null
  _sum: WorkHoursSumAggregateOutputType | null
  _min: WorkHoursMinAggregateOutputType | null
  _max: WorkHoursMaxAggregateOutputType | null
}

export type GetWorkHoursGroupByPayload<T extends WorkHoursGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkHoursGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkHoursGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkHoursGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkHoursGroupByOutputType[P]>
      }
    >
  >



export type WorkHoursWhereInput = {
  AND?: Prisma.WorkHoursWhereInput | Prisma.WorkHoursWhereInput[]
  OR?: Prisma.WorkHoursWhereInput[]
  NOT?: Prisma.WorkHoursWhereInput | Prisma.WorkHoursWhereInput[]
  id?: Prisma.StringFilter<"WorkHours"> | string
  teamId?: Prisma.StringFilter<"WorkHours"> | string
  projectId?: Prisma.StringFilter<"WorkHours"> | string
  hoursWorked?: Prisma.FloatFilter<"WorkHours"> | number
  date?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  description?: Prisma.StringNullableFilter<"WorkHours"> | string | null
  createdAt?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type WorkHoursOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  team?: Prisma.TeamOrderByWithRelationInput
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type WorkHoursWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkHoursWhereInput | Prisma.WorkHoursWhereInput[]
  OR?: Prisma.WorkHoursWhereInput[]
  NOT?: Prisma.WorkHoursWhereInput | Prisma.WorkHoursWhereInput[]
  teamId?: Prisma.StringFilter<"WorkHours"> | string
  projectId?: Prisma.StringFilter<"WorkHours"> | string
  hoursWorked?: Prisma.FloatFilter<"WorkHours"> | number
  date?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  description?: Prisma.StringNullableFilter<"WorkHours"> | string | null
  createdAt?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id">

export type WorkHoursOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WorkHoursCountOrderByAggregateInput
  _avg?: Prisma.WorkHoursAvgOrderByAggregateInput
  _max?: Prisma.WorkHoursMaxOrderByAggregateInput
  _min?: Prisma.WorkHoursMinOrderByAggregateInput
  _sum?: Prisma.WorkHoursSumOrderByAggregateInput
}

export type WorkHoursScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkHoursScalarWhereWithAggregatesInput | Prisma.WorkHoursScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkHoursScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkHoursScalarWhereWithAggregatesInput | Prisma.WorkHoursScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkHours"> | string
  teamId?: Prisma.StringWithAggregatesFilter<"WorkHours"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"WorkHours"> | string
  hoursWorked?: Prisma.FloatWithAggregatesFilter<"WorkHours"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"WorkHours"> | Date | string
  description?: Prisma.StringNullableWithAggregatesFilter<"WorkHours"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkHours"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WorkHours"> | Date | string
}

export type WorkHoursCreateInput = {
  id?: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  team: Prisma.TeamCreateNestedOneWithoutWorkHoursInput
  project: Prisma.ProjectCreateNestedOneWithoutWorkHoursInput
}

export type WorkHoursUncheckedCreateInput = {
  id?: string
  teamId: string
  projectId: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkHoursUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  team?: Prisma.TeamUpdateOneRequiredWithoutWorkHoursNestedInput
  project?: Prisma.ProjectUpdateOneRequiredWithoutWorkHoursNestedInput
}

export type WorkHoursUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkHoursCreateManyInput = {
  id?: string
  teamId: string
  projectId: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkHoursUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkHoursUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkHoursListRelationFilter = {
  every?: Prisma.WorkHoursWhereInput
  some?: Prisma.WorkHoursWhereInput
  none?: Prisma.WorkHoursWhereInput
}

export type WorkHoursOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkHoursCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkHoursAvgOrderByAggregateInput = {
  hoursWorked?: Prisma.SortOrder
}

export type WorkHoursMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkHoursMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  hoursWorked?: Prisma.SortOrder
  date?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkHoursSumOrderByAggregateInput = {
  hoursWorked?: Prisma.SortOrder
}

export type WorkHoursCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutTeamInput, Prisma.WorkHoursUncheckedCreateWithoutTeamInput> | Prisma.WorkHoursCreateWithoutTeamInput[] | Prisma.WorkHoursUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutTeamInput | Prisma.WorkHoursCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.WorkHoursCreateManyTeamInputEnvelope
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
}

export type WorkHoursUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutTeamInput, Prisma.WorkHoursUncheckedCreateWithoutTeamInput> | Prisma.WorkHoursCreateWithoutTeamInput[] | Prisma.WorkHoursUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutTeamInput | Prisma.WorkHoursCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.WorkHoursCreateManyTeamInputEnvelope
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
}

export type WorkHoursUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutTeamInput, Prisma.WorkHoursUncheckedCreateWithoutTeamInput> | Prisma.WorkHoursCreateWithoutTeamInput[] | Prisma.WorkHoursUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutTeamInput | Prisma.WorkHoursCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.WorkHoursUpsertWithWhereUniqueWithoutTeamInput | Prisma.WorkHoursUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.WorkHoursCreateManyTeamInputEnvelope
  set?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  disconnect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  delete?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  update?: Prisma.WorkHoursUpdateWithWhereUniqueWithoutTeamInput | Prisma.WorkHoursUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.WorkHoursUpdateManyWithWhereWithoutTeamInput | Prisma.WorkHoursUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.WorkHoursScalarWhereInput | Prisma.WorkHoursScalarWhereInput[]
}

export type WorkHoursUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutTeamInput, Prisma.WorkHoursUncheckedCreateWithoutTeamInput> | Prisma.WorkHoursCreateWithoutTeamInput[] | Prisma.WorkHoursUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutTeamInput | Prisma.WorkHoursCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.WorkHoursUpsertWithWhereUniqueWithoutTeamInput | Prisma.WorkHoursUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.WorkHoursCreateManyTeamInputEnvelope
  set?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  disconnect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  delete?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  update?: Prisma.WorkHoursUpdateWithWhereUniqueWithoutTeamInput | Prisma.WorkHoursUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.WorkHoursUpdateManyWithWhereWithoutTeamInput | Prisma.WorkHoursUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.WorkHoursScalarWhereInput | Prisma.WorkHoursScalarWhereInput[]
}

export type WorkHoursCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutProjectInput, Prisma.WorkHoursUncheckedCreateWithoutProjectInput> | Prisma.WorkHoursCreateWithoutProjectInput[] | Prisma.WorkHoursUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutProjectInput | Prisma.WorkHoursCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.WorkHoursCreateManyProjectInputEnvelope
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
}

export type WorkHoursUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutProjectInput, Prisma.WorkHoursUncheckedCreateWithoutProjectInput> | Prisma.WorkHoursCreateWithoutProjectInput[] | Prisma.WorkHoursUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutProjectInput | Prisma.WorkHoursCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.WorkHoursCreateManyProjectInputEnvelope
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
}

export type WorkHoursUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutProjectInput, Prisma.WorkHoursUncheckedCreateWithoutProjectInput> | Prisma.WorkHoursCreateWithoutProjectInput[] | Prisma.WorkHoursUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutProjectInput | Prisma.WorkHoursCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.WorkHoursUpsertWithWhereUniqueWithoutProjectInput | Prisma.WorkHoursUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.WorkHoursCreateManyProjectInputEnvelope
  set?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  disconnect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  delete?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  update?: Prisma.WorkHoursUpdateWithWhereUniqueWithoutProjectInput | Prisma.WorkHoursUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.WorkHoursUpdateManyWithWhereWithoutProjectInput | Prisma.WorkHoursUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.WorkHoursScalarWhereInput | Prisma.WorkHoursScalarWhereInput[]
}

export type WorkHoursUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.WorkHoursCreateWithoutProjectInput, Prisma.WorkHoursUncheckedCreateWithoutProjectInput> | Prisma.WorkHoursCreateWithoutProjectInput[] | Prisma.WorkHoursUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.WorkHoursCreateOrConnectWithoutProjectInput | Prisma.WorkHoursCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.WorkHoursUpsertWithWhereUniqueWithoutProjectInput | Prisma.WorkHoursUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.WorkHoursCreateManyProjectInputEnvelope
  set?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  disconnect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  delete?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  connect?: Prisma.WorkHoursWhereUniqueInput | Prisma.WorkHoursWhereUniqueInput[]
  update?: Prisma.WorkHoursUpdateWithWhereUniqueWithoutProjectInput | Prisma.WorkHoursUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.WorkHoursUpdateManyWithWhereWithoutProjectInput | Prisma.WorkHoursUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.WorkHoursScalarWhereInput | Prisma.WorkHoursScalarWhereInput[]
}

export type WorkHoursCreateWithoutTeamInput = {
  id?: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutWorkHoursInput
}

export type WorkHoursUncheckedCreateWithoutTeamInput = {
  id?: string
  projectId: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkHoursCreateOrConnectWithoutTeamInput = {
  where: Prisma.WorkHoursWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkHoursCreateWithoutTeamInput, Prisma.WorkHoursUncheckedCreateWithoutTeamInput>
}

export type WorkHoursCreateManyTeamInputEnvelope = {
  data: Prisma.WorkHoursCreateManyTeamInput | Prisma.WorkHoursCreateManyTeamInput[]
}

export type WorkHoursUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.WorkHoursWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkHoursUpdateWithoutTeamInput, Prisma.WorkHoursUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.WorkHoursCreateWithoutTeamInput, Prisma.WorkHoursUncheckedCreateWithoutTeamInput>
}

export type WorkHoursUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.WorkHoursWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkHoursUpdateWithoutTeamInput, Prisma.WorkHoursUncheckedUpdateWithoutTeamInput>
}

export type WorkHoursUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.WorkHoursScalarWhereInput
  data: Prisma.XOR<Prisma.WorkHoursUpdateManyMutationInput, Prisma.WorkHoursUncheckedUpdateManyWithoutTeamInput>
}

export type WorkHoursScalarWhereInput = {
  AND?: Prisma.WorkHoursScalarWhereInput | Prisma.WorkHoursScalarWhereInput[]
  OR?: Prisma.WorkHoursScalarWhereInput[]
  NOT?: Prisma.WorkHoursScalarWhereInput | Prisma.WorkHoursScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkHours"> | string
  teamId?: Prisma.StringFilter<"WorkHours"> | string
  projectId?: Prisma.StringFilter<"WorkHours"> | string
  hoursWorked?: Prisma.FloatFilter<"WorkHours"> | number
  date?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  description?: Prisma.StringNullableFilter<"WorkHours"> | string | null
  createdAt?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkHours"> | Date | string
}

export type WorkHoursCreateWithoutProjectInput = {
  id?: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  team: Prisma.TeamCreateNestedOneWithoutWorkHoursInput
}

export type WorkHoursUncheckedCreateWithoutProjectInput = {
  id?: string
  teamId: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkHoursCreateOrConnectWithoutProjectInput = {
  where: Prisma.WorkHoursWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkHoursCreateWithoutProjectInput, Prisma.WorkHoursUncheckedCreateWithoutProjectInput>
}

export type WorkHoursCreateManyProjectInputEnvelope = {
  data: Prisma.WorkHoursCreateManyProjectInput | Prisma.WorkHoursCreateManyProjectInput[]
}

export type WorkHoursUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.WorkHoursWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkHoursUpdateWithoutProjectInput, Prisma.WorkHoursUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.WorkHoursCreateWithoutProjectInput, Prisma.WorkHoursUncheckedCreateWithoutProjectInput>
}

export type WorkHoursUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.WorkHoursWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkHoursUpdateWithoutProjectInput, Prisma.WorkHoursUncheckedUpdateWithoutProjectInput>
}

export type WorkHoursUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.WorkHoursScalarWhereInput
  data: Prisma.XOR<Prisma.WorkHoursUpdateManyMutationInput, Prisma.WorkHoursUncheckedUpdateManyWithoutProjectInput>
}

export type WorkHoursCreateManyTeamInput = {
  id?: string
  projectId: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkHoursUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutWorkHoursNestedInput
}

export type WorkHoursUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkHoursUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkHoursCreateManyProjectInput = {
  id?: string
  teamId: string
  hoursWorked: number
  date: Date | string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkHoursUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  team?: Prisma.TeamUpdateOneRequiredWithoutWorkHoursNestedInput
}

export type WorkHoursUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkHoursUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  hoursWorked?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WorkHoursSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  projectId?: boolean
  hoursWorked?: boolean
  date?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workHours"]>

export type WorkHoursSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  projectId?: boolean
  hoursWorked?: boolean
  date?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workHours"]>

export type WorkHoursSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  projectId?: boolean
  hoursWorked?: boolean
  date?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workHours"]>

export type WorkHoursSelectScalar = {
  id?: boolean
  teamId?: boolean
  projectId?: boolean
  hoursWorked?: boolean
  date?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WorkHoursOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "teamId" | "projectId" | "hoursWorked" | "date" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["workHours"]>
export type WorkHoursInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type WorkHoursIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type WorkHoursIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $WorkHoursPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkHours"
  objects: {
    team: Prisma.$TeamPayload<ExtArgs>
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    teamId: string
    projectId: string
    hoursWorked: number
    date: Date
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["workHours"]>
  composites: {}
}

export type WorkHoursGetPayload<S extends boolean | null | undefined | WorkHoursDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload, S>

export type WorkHoursCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkHoursFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkHoursCountAggregateInputType | true
  }

export interface WorkHoursDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkHours'], meta: { name: 'WorkHours' } }
  /**
   * Find zero or one WorkHours that matches the filter.
   * @param {WorkHoursFindUniqueArgs} args - Arguments to find a WorkHours
   * @example
   * // Get one WorkHours
   * const workHours = await prisma.workHours.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkHoursFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkHoursFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkHours that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkHoursFindUniqueOrThrowArgs} args - Arguments to find a WorkHours
   * @example
   * // Get one WorkHours
   * const workHours = await prisma.workHours.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkHoursFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkHoursFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkHours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkHoursFindFirstArgs} args - Arguments to find a WorkHours
   * @example
   * // Get one WorkHours
   * const workHours = await prisma.workHours.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkHoursFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkHoursFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkHours that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkHoursFindFirstOrThrowArgs} args - Arguments to find a WorkHours
   * @example
   * // Get one WorkHours
   * const workHours = await prisma.workHours.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkHoursFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkHoursFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkHours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkHoursFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkHours
   * const workHours = await prisma.workHours.findMany()
   * 
   * // Get first 10 WorkHours
   * const workHours = await prisma.workHours.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workHoursWithIdOnly = await prisma.workHours.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkHoursFindManyArgs>(args?: Prisma.SelectSubset<T, WorkHoursFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkHours.
   * @param {WorkHoursCreateArgs} args - Arguments to create a WorkHours.
   * @example
   * // Create one WorkHours
   * const WorkHours = await prisma.workHours.create({
   *   data: {
   *     // ... data to create a WorkHours
   *   }
   * })
   * 
   */
  create<T extends WorkHoursCreateArgs>(args: Prisma.SelectSubset<T, WorkHoursCreateArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkHours.
   * @param {WorkHoursCreateManyArgs} args - Arguments to create many WorkHours.
   * @example
   * // Create many WorkHours
   * const workHours = await prisma.workHours.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkHoursCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkHoursCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkHours and returns the data saved in the database.
   * @param {WorkHoursCreateManyAndReturnArgs} args - Arguments to create many WorkHours.
   * @example
   * // Create many WorkHours
   * const workHours = await prisma.workHours.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkHours and only return the `id`
   * const workHoursWithIdOnly = await prisma.workHours.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkHoursCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkHoursCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkHours.
   * @param {WorkHoursDeleteArgs} args - Arguments to delete one WorkHours.
   * @example
   * // Delete one WorkHours
   * const WorkHours = await prisma.workHours.delete({
   *   where: {
   *     // ... filter to delete one WorkHours
   *   }
   * })
   * 
   */
  delete<T extends WorkHoursDeleteArgs>(args: Prisma.SelectSubset<T, WorkHoursDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkHours.
   * @param {WorkHoursUpdateArgs} args - Arguments to update one WorkHours.
   * @example
   * // Update one WorkHours
   * const workHours = await prisma.workHours.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkHoursUpdateArgs>(args: Prisma.SelectSubset<T, WorkHoursUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkHours.
   * @param {WorkHoursDeleteManyArgs} args - Arguments to filter WorkHours to delete.
   * @example
   * // Delete a few WorkHours
   * const { count } = await prisma.workHours.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkHoursDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkHoursDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkHoursUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkHours
   * const workHours = await prisma.workHours.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkHoursUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkHoursUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkHours and returns the data updated in the database.
   * @param {WorkHoursUpdateManyAndReturnArgs} args - Arguments to update many WorkHours.
   * @example
   * // Update many WorkHours
   * const workHours = await prisma.workHours.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkHours and only return the `id`
   * const workHoursWithIdOnly = await prisma.workHours.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkHoursUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkHoursUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkHours.
   * @param {WorkHoursUpsertArgs} args - Arguments to update or create a WorkHours.
   * @example
   * // Update or create a WorkHours
   * const workHours = await prisma.workHours.upsert({
   *   create: {
   *     // ... data to create a WorkHours
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkHours we want to update
   *   }
   * })
   */
  upsert<T extends WorkHoursUpsertArgs>(args: Prisma.SelectSubset<T, WorkHoursUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkHoursClient<runtime.Types.Result.GetResult<Prisma.$WorkHoursPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkHoursCountArgs} args - Arguments to filter WorkHours to count.
   * @example
   * // Count the number of WorkHours
   * const count = await prisma.workHours.count({
   *   where: {
   *     // ... the filter for the WorkHours we want to count
   *   }
   * })
  **/
  count<T extends WorkHoursCountArgs>(
    args?: Prisma.Subset<T, WorkHoursCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkHoursCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkHoursAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkHoursAggregateArgs>(args: Prisma.Subset<T, WorkHoursAggregateArgs>): Prisma.PrismaPromise<GetWorkHoursAggregateType<T>>

  /**
   * Group by WorkHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkHoursGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkHoursGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkHoursGroupByArgs['orderBy'] }
      : { orderBy?: WorkHoursGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkHoursGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkHoursGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkHours model
 */
readonly fields: WorkHoursFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkHours.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkHoursClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkHours model
 */
export interface WorkHoursFieldRefs {
  readonly id: Prisma.FieldRef<"WorkHours", 'String'>
  readonly teamId: Prisma.FieldRef<"WorkHours", 'String'>
  readonly projectId: Prisma.FieldRef<"WorkHours", 'String'>
  readonly hoursWorked: Prisma.FieldRef<"WorkHours", 'Float'>
  readonly date: Prisma.FieldRef<"WorkHours", 'DateTime'>
  readonly description: Prisma.FieldRef<"WorkHours", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorkHours", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WorkHours", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkHours findUnique
 */
export type WorkHoursFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * Filter, which WorkHours to fetch.
   */
  where: Prisma.WorkHoursWhereUniqueInput
}

/**
 * WorkHours findUniqueOrThrow
 */
export type WorkHoursFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * Filter, which WorkHours to fetch.
   */
  where: Prisma.WorkHoursWhereUniqueInput
}

/**
 * WorkHours findFirst
 */
export type WorkHoursFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * Filter, which WorkHours to fetch.
   */
  where?: Prisma.WorkHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkHours to fetch.
   */
  orderBy?: Prisma.WorkHoursOrderByWithRelationInput | Prisma.WorkHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkHours.
   */
  cursor?: Prisma.WorkHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkHours.
   */
  distinct?: Prisma.WorkHoursScalarFieldEnum | Prisma.WorkHoursScalarFieldEnum[]
}

/**
 * WorkHours findFirstOrThrow
 */
export type WorkHoursFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * Filter, which WorkHours to fetch.
   */
  where?: Prisma.WorkHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkHours to fetch.
   */
  orderBy?: Prisma.WorkHoursOrderByWithRelationInput | Prisma.WorkHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkHours.
   */
  cursor?: Prisma.WorkHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkHours.
   */
  distinct?: Prisma.WorkHoursScalarFieldEnum | Prisma.WorkHoursScalarFieldEnum[]
}

/**
 * WorkHours findMany
 */
export type WorkHoursFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * Filter, which WorkHours to fetch.
   */
  where?: Prisma.WorkHoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkHours to fetch.
   */
  orderBy?: Prisma.WorkHoursOrderByWithRelationInput | Prisma.WorkHoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkHours.
   */
  cursor?: Prisma.WorkHoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkHours.
   */
  distinct?: Prisma.WorkHoursScalarFieldEnum | Prisma.WorkHoursScalarFieldEnum[]
}

/**
 * WorkHours create
 */
export type WorkHoursCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkHours.
   */
  data: Prisma.XOR<Prisma.WorkHoursCreateInput, Prisma.WorkHoursUncheckedCreateInput>
}

/**
 * WorkHours createMany
 */
export type WorkHoursCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkHours.
   */
  data: Prisma.WorkHoursCreateManyInput | Prisma.WorkHoursCreateManyInput[]
}

/**
 * WorkHours createManyAndReturn
 */
export type WorkHoursCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * The data used to create many WorkHours.
   */
  data: Prisma.WorkHoursCreateManyInput | Prisma.WorkHoursCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkHours update
 */
export type WorkHoursUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkHours.
   */
  data: Prisma.XOR<Prisma.WorkHoursUpdateInput, Prisma.WorkHoursUncheckedUpdateInput>
  /**
   * Choose, which WorkHours to update.
   */
  where: Prisma.WorkHoursWhereUniqueInput
}

/**
 * WorkHours updateMany
 */
export type WorkHoursUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkHours.
   */
  data: Prisma.XOR<Prisma.WorkHoursUpdateManyMutationInput, Prisma.WorkHoursUncheckedUpdateManyInput>
  /**
   * Filter which WorkHours to update
   */
  where?: Prisma.WorkHoursWhereInput
  /**
   * Limit how many WorkHours to update.
   */
  limit?: number
}

/**
 * WorkHours updateManyAndReturn
 */
export type WorkHoursUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * The data used to update WorkHours.
   */
  data: Prisma.XOR<Prisma.WorkHoursUpdateManyMutationInput, Prisma.WorkHoursUncheckedUpdateManyInput>
  /**
   * Filter which WorkHours to update
   */
  where?: Prisma.WorkHoursWhereInput
  /**
   * Limit how many WorkHours to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkHours upsert
 */
export type WorkHoursUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkHours to update in case it exists.
   */
  where: Prisma.WorkHoursWhereUniqueInput
  /**
   * In case the WorkHours found by the `where` argument doesn't exist, create a new WorkHours with this data.
   */
  create: Prisma.XOR<Prisma.WorkHoursCreateInput, Prisma.WorkHoursUncheckedCreateInput>
  /**
   * In case the WorkHours was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkHoursUpdateInput, Prisma.WorkHoursUncheckedUpdateInput>
}

/**
 * WorkHours delete
 */
export type WorkHoursDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
  /**
   * Filter which WorkHours to delete.
   */
  where: Prisma.WorkHoursWhereUniqueInput
}

/**
 * WorkHours deleteMany
 */
export type WorkHoursDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkHours to delete
   */
  where?: Prisma.WorkHoursWhereInput
  /**
   * Limit how many WorkHours to delete.
   */
  limit?: number
}

/**
 * WorkHours without action
 */
export type WorkHoursDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkHours
   */
  select?: Prisma.WorkHoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkHours
   */
  omit?: Prisma.WorkHoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkHoursInclude<ExtArgs> | null
}
