
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Team: 'Team',
  Client: 'Client',
  Project: 'Project',
  Material: 'Material',
  InventoryItem: 'InventoryItem',
  InventoryMovement: 'InventoryMovement',
  ProjectTeamAssignment: 'ProjectTeamAssignment',
  WorkHours: 'WorkHours',
  MaterialsInProject: 'MaterialsInProject'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  hourlyRate: 'hourlyRate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamScalarFieldEnum = (typeof TeamScalarFieldEnum)[keyof typeof TeamScalarFieldEnum]


export const ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  address: 'address',
  city: 'city',
  province: 'province',
  postalCode: 'postalCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClientScalarFieldEnum = (typeof ClientScalarFieldEnum)[keyof typeof ClientScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  clientId: 'clientId',
  status: 'status',
  location: 'location',
  estimatedHours: 'estimatedHours',
  actualHours: 'actualHours',
  estimatedCost: 'estimatedCost',
  actualCost: 'actualCost',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const MaterialScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  category: 'category',
  description: 'description',
  unitPrice: 'unitPrice',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MaterialScalarFieldEnum = (typeof MaterialScalarFieldEnum)[keyof typeof MaterialScalarFieldEnum]


export const InventoryItemScalarFieldEnum = {
  id: 'id',
  materialId: 'materialId',
  quantity: 'quantity',
  location: 'location',
  minThreshold: 'minThreshold',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type InventoryItemScalarFieldEnum = (typeof InventoryItemScalarFieldEnum)[keyof typeof InventoryItemScalarFieldEnum]


export const InventoryMovementScalarFieldEnum = {
  id: 'id',
  materialId: 'materialId',
  type: 'type',
  quantity: 'quantity',
  reason: 'reason',
  reference: 'reference',
  date: 'date',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
} as const

export type InventoryMovementScalarFieldEnum = (typeof InventoryMovementScalarFieldEnum)[keyof typeof InventoryMovementScalarFieldEnum]


export const ProjectTeamAssignmentScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  teamId: 'teamId',
  role: 'role',
  assignedDate: 'assignedDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectTeamAssignmentScalarFieldEnum = (typeof ProjectTeamAssignmentScalarFieldEnum)[keyof typeof ProjectTeamAssignmentScalarFieldEnum]


export const WorkHoursScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  projectId: 'projectId',
  hoursWorked: 'hoursWorked',
  date: 'date',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkHoursScalarFieldEnum = (typeof WorkHoursScalarFieldEnum)[keyof typeof WorkHoursScalarFieldEnum]


export const MaterialsInProjectScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  materialId: 'materialId',
  quantityUsed: 'quantityUsed',
  date: 'date',
  createdAt: 'createdAt'
} as const

export type MaterialsInProjectScalarFieldEnum = (typeof MaterialsInProjectScalarFieldEnum)[keyof typeof MaterialsInProjectScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

