
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MaterialsInProject` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MaterialsInProject
 * 
 */
export type MaterialsInProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$MaterialsInProjectPayload>

export type AggregateMaterialsInProject = {
  _count: MaterialsInProjectCountAggregateOutputType | null
  _avg: MaterialsInProjectAvgAggregateOutputType | null
  _sum: MaterialsInProjectSumAggregateOutputType | null
  _min: MaterialsInProjectMinAggregateOutputType | null
  _max: MaterialsInProjectMaxAggregateOutputType | null
}

export type MaterialsInProjectAvgAggregateOutputType = {
  quantityUsed: number | null
}

export type MaterialsInProjectSumAggregateOutputType = {
  quantityUsed: number | null
}

export type MaterialsInProjectMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  materialId: string | null
  quantityUsed: number | null
  date: Date | null
  createdAt: Date | null
}

export type MaterialsInProjectMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  materialId: string | null
  quantityUsed: number | null
  date: Date | null
  createdAt: Date | null
}

export type MaterialsInProjectCountAggregateOutputType = {
  id: number
  projectId: number
  materialId: number
  quantityUsed: number
  date: number
  createdAt: number
  _all: number
}


export type MaterialsInProjectAvgAggregateInputType = {
  quantityUsed?: true
}

export type MaterialsInProjectSumAggregateInputType = {
  quantityUsed?: true
}

export type MaterialsInProjectMinAggregateInputType = {
  id?: true
  projectId?: true
  materialId?: true
  quantityUsed?: true
  date?: true
  createdAt?: true
}

export type MaterialsInProjectMaxAggregateInputType = {
  id?: true
  projectId?: true
  materialId?: true
  quantityUsed?: true
  date?: true
  createdAt?: true
}

export type MaterialsInProjectCountAggregateInputType = {
  id?: true
  projectId?: true
  materialId?: true
  quantityUsed?: true
  date?: true
  createdAt?: true
  _all?: true
}

export type MaterialsInProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaterialsInProject to aggregate.
   */
  where?: Prisma.MaterialsInProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialsInProjects to fetch.
   */
  orderBy?: Prisma.MaterialsInProjectOrderByWithRelationInput | Prisma.MaterialsInProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaterialsInProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialsInProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialsInProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MaterialsInProjects
  **/
  _count?: true | MaterialsInProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MaterialsInProjectAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MaterialsInProjectSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaterialsInProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaterialsInProjectMaxAggregateInputType
}

export type GetMaterialsInProjectAggregateType<T extends MaterialsInProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateMaterialsInProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaterialsInProject[P]>
    : Prisma.GetScalarType<T[P], AggregateMaterialsInProject[P]>
}




export type MaterialsInProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaterialsInProjectWhereInput
  orderBy?: Prisma.MaterialsInProjectOrderByWithAggregationInput | Prisma.MaterialsInProjectOrderByWithAggregationInput[]
  by: Prisma.MaterialsInProjectScalarFieldEnum[] | Prisma.MaterialsInProjectScalarFieldEnum
  having?: Prisma.MaterialsInProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaterialsInProjectCountAggregateInputType | true
  _avg?: MaterialsInProjectAvgAggregateInputType
  _sum?: MaterialsInProjectSumAggregateInputType
  _min?: MaterialsInProjectMinAggregateInputType
  _max?: MaterialsInProjectMaxAggregateInputType
}

export type MaterialsInProjectGroupByOutputType = {
  id: string
  projectId: string
  materialId: string
  quantityUsed: number
  date: Date
  createdAt: Date
  _count: MaterialsInProjectCountAggregateOutputType | null
  _avg: MaterialsInProjectAvgAggregateOutputType | null
  _sum: MaterialsInProjectSumAggregateOutputType | null
  _min: MaterialsInProjectMinAggregateOutputType | null
  _max: MaterialsInProjectMaxAggregateOutputType | null
}

export type GetMaterialsInProjectGroupByPayload<T extends MaterialsInProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaterialsInProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaterialsInProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaterialsInProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaterialsInProjectGroupByOutputType[P]>
      }
    >
  >



export type MaterialsInProjectWhereInput = {
  AND?: Prisma.MaterialsInProjectWhereInput | Prisma.MaterialsInProjectWhereInput[]
  OR?: Prisma.MaterialsInProjectWhereInput[]
  NOT?: Prisma.MaterialsInProjectWhereInput | Prisma.MaterialsInProjectWhereInput[]
  id?: Prisma.StringFilter<"MaterialsInProject"> | string
  projectId?: Prisma.StringFilter<"MaterialsInProject"> | string
  materialId?: Prisma.StringFilter<"MaterialsInProject"> | string
  quantityUsed?: Prisma.IntFilter<"MaterialsInProject"> | number
  date?: Prisma.DateTimeFilter<"MaterialsInProject"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MaterialsInProject"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  material?: Prisma.XOR<Prisma.MaterialScalarRelationFilter, Prisma.MaterialWhereInput>
}

export type MaterialsInProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  quantityUsed?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  material?: Prisma.MaterialOrderByWithRelationInput
}

export type MaterialsInProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MaterialsInProjectWhereInput | Prisma.MaterialsInProjectWhereInput[]
  OR?: Prisma.MaterialsInProjectWhereInput[]
  NOT?: Prisma.MaterialsInProjectWhereInput | Prisma.MaterialsInProjectWhereInput[]
  projectId?: Prisma.StringFilter<"MaterialsInProject"> | string
  materialId?: Prisma.StringFilter<"MaterialsInProject"> | string
  quantityUsed?: Prisma.IntFilter<"MaterialsInProject"> | number
  date?: Prisma.DateTimeFilter<"MaterialsInProject"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MaterialsInProject"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  material?: Prisma.XOR<Prisma.MaterialScalarRelationFilter, Prisma.MaterialWhereInput>
}, "id">

export type MaterialsInProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  quantityUsed?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MaterialsInProjectCountOrderByAggregateInput
  _avg?: Prisma.MaterialsInProjectAvgOrderByAggregateInput
  _max?: Prisma.MaterialsInProjectMaxOrderByAggregateInput
  _min?: Prisma.MaterialsInProjectMinOrderByAggregateInput
  _sum?: Prisma.MaterialsInProjectSumOrderByAggregateInput
}

export type MaterialsInProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaterialsInProjectScalarWhereWithAggregatesInput | Prisma.MaterialsInProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaterialsInProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaterialsInProjectScalarWhereWithAggregatesInput | Prisma.MaterialsInProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MaterialsInProject"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"MaterialsInProject"> | string
  materialId?: Prisma.StringWithAggregatesFilter<"MaterialsInProject"> | string
  quantityUsed?: Prisma.IntWithAggregatesFilter<"MaterialsInProject"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"MaterialsInProject"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MaterialsInProject"> | Date | string
}

export type MaterialsInProjectCreateInput = {
  id?: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutMaterialsUsedInput
  material: Prisma.MaterialCreateNestedOneWithoutProjectUsageInput
}

export type MaterialsInProjectUncheckedCreateInput = {
  id?: string
  projectId: string
  materialId: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
}

export type MaterialsInProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutMaterialsUsedNestedInput
  material?: Prisma.MaterialUpdateOneRequiredWithoutProjectUsageNestedInput
}

export type MaterialsInProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialsInProjectCreateManyInput = {
  id?: string
  projectId: string
  materialId: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
}

export type MaterialsInProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialsInProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialsInProjectListRelationFilter = {
  every?: Prisma.MaterialsInProjectWhereInput
  some?: Prisma.MaterialsInProjectWhereInput
  none?: Prisma.MaterialsInProjectWhereInput
}

export type MaterialsInProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MaterialsInProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  quantityUsed?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MaterialsInProjectAvgOrderByAggregateInput = {
  quantityUsed?: Prisma.SortOrder
}

export type MaterialsInProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  quantityUsed?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MaterialsInProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  quantityUsed?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MaterialsInProjectSumOrderByAggregateInput = {
  quantityUsed?: Prisma.SortOrder
}

export type MaterialsInProjectCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput> | Prisma.MaterialsInProjectCreateWithoutProjectInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput | Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyProjectInputEnvelope
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
}

export type MaterialsInProjectUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput> | Prisma.MaterialsInProjectCreateWithoutProjectInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput | Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyProjectInputEnvelope
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
}

export type MaterialsInProjectUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput> | Prisma.MaterialsInProjectCreateWithoutProjectInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput | Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyProjectInputEnvelope
  set?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  disconnect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  delete?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  update?: Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.MaterialsInProjectUpdateManyWithWhereWithoutProjectInput | Prisma.MaterialsInProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.MaterialsInProjectScalarWhereInput | Prisma.MaterialsInProjectScalarWhereInput[]
}

export type MaterialsInProjectUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput> | Prisma.MaterialsInProjectCreateWithoutProjectInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput | Prisma.MaterialsInProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyProjectInputEnvelope
  set?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  disconnect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  delete?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  update?: Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.MaterialsInProjectUpdateManyWithWhereWithoutProjectInput | Prisma.MaterialsInProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.MaterialsInProjectScalarWhereInput | Prisma.MaterialsInProjectScalarWhereInput[]
}

export type MaterialsInProjectCreateNestedManyWithoutMaterialInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput> | Prisma.MaterialsInProjectCreateWithoutMaterialInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput | Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyMaterialInputEnvelope
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
}

export type MaterialsInProjectUncheckedCreateNestedManyWithoutMaterialInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput> | Prisma.MaterialsInProjectCreateWithoutMaterialInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput | Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyMaterialInputEnvelope
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
}

export type MaterialsInProjectUpdateManyWithoutMaterialNestedInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput> | Prisma.MaterialsInProjectCreateWithoutMaterialInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput | Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput[]
  upsert?: Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutMaterialInput | Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutMaterialInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyMaterialInputEnvelope
  set?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  disconnect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  delete?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  update?: Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutMaterialInput | Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutMaterialInput[]
  updateMany?: Prisma.MaterialsInProjectUpdateManyWithWhereWithoutMaterialInput | Prisma.MaterialsInProjectUpdateManyWithWhereWithoutMaterialInput[]
  deleteMany?: Prisma.MaterialsInProjectScalarWhereInput | Prisma.MaterialsInProjectScalarWhereInput[]
}

export type MaterialsInProjectUncheckedUpdateManyWithoutMaterialNestedInput = {
  create?: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput> | Prisma.MaterialsInProjectCreateWithoutMaterialInput[] | Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput | Prisma.MaterialsInProjectCreateOrConnectWithoutMaterialInput[]
  upsert?: Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutMaterialInput | Prisma.MaterialsInProjectUpsertWithWhereUniqueWithoutMaterialInput[]
  createMany?: Prisma.MaterialsInProjectCreateManyMaterialInputEnvelope
  set?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  disconnect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  delete?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  connect?: Prisma.MaterialsInProjectWhereUniqueInput | Prisma.MaterialsInProjectWhereUniqueInput[]
  update?: Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutMaterialInput | Prisma.MaterialsInProjectUpdateWithWhereUniqueWithoutMaterialInput[]
  updateMany?: Prisma.MaterialsInProjectUpdateManyWithWhereWithoutMaterialInput | Prisma.MaterialsInProjectUpdateManyWithWhereWithoutMaterialInput[]
  deleteMany?: Prisma.MaterialsInProjectScalarWhereInput | Prisma.MaterialsInProjectScalarWhereInput[]
}

export type MaterialsInProjectCreateWithoutProjectInput = {
  id?: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
  material: Prisma.MaterialCreateNestedOneWithoutProjectUsageInput
}

export type MaterialsInProjectUncheckedCreateWithoutProjectInput = {
  id?: string
  materialId: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
}

export type MaterialsInProjectCreateOrConnectWithoutProjectInput = {
  where: Prisma.MaterialsInProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput>
}

export type MaterialsInProjectCreateManyProjectInputEnvelope = {
  data: Prisma.MaterialsInProjectCreateManyProjectInput | Prisma.MaterialsInProjectCreateManyProjectInput[]
}

export type MaterialsInProjectUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.MaterialsInProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.MaterialsInProjectUpdateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedCreateWithoutProjectInput>
}

export type MaterialsInProjectUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.MaterialsInProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.MaterialsInProjectUpdateWithoutProjectInput, Prisma.MaterialsInProjectUncheckedUpdateWithoutProjectInput>
}

export type MaterialsInProjectUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.MaterialsInProjectScalarWhereInput
  data: Prisma.XOR<Prisma.MaterialsInProjectUpdateManyMutationInput, Prisma.MaterialsInProjectUncheckedUpdateManyWithoutProjectInput>
}

export type MaterialsInProjectScalarWhereInput = {
  AND?: Prisma.MaterialsInProjectScalarWhereInput | Prisma.MaterialsInProjectScalarWhereInput[]
  OR?: Prisma.MaterialsInProjectScalarWhereInput[]
  NOT?: Prisma.MaterialsInProjectScalarWhereInput | Prisma.MaterialsInProjectScalarWhereInput[]
  id?: Prisma.StringFilter<"MaterialsInProject"> | string
  projectId?: Prisma.StringFilter<"MaterialsInProject"> | string
  materialId?: Prisma.StringFilter<"MaterialsInProject"> | string
  quantityUsed?: Prisma.IntFilter<"MaterialsInProject"> | number
  date?: Prisma.DateTimeFilter<"MaterialsInProject"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MaterialsInProject"> | Date | string
}

export type MaterialsInProjectCreateWithoutMaterialInput = {
  id?: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutMaterialsUsedInput
}

export type MaterialsInProjectUncheckedCreateWithoutMaterialInput = {
  id?: string
  projectId: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
}

export type MaterialsInProjectCreateOrConnectWithoutMaterialInput = {
  where: Prisma.MaterialsInProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput>
}

export type MaterialsInProjectCreateManyMaterialInputEnvelope = {
  data: Prisma.MaterialsInProjectCreateManyMaterialInput | Prisma.MaterialsInProjectCreateManyMaterialInput[]
}

export type MaterialsInProjectUpsertWithWhereUniqueWithoutMaterialInput = {
  where: Prisma.MaterialsInProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.MaterialsInProjectUpdateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedUpdateWithoutMaterialInput>
  create: Prisma.XOR<Prisma.MaterialsInProjectCreateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedCreateWithoutMaterialInput>
}

export type MaterialsInProjectUpdateWithWhereUniqueWithoutMaterialInput = {
  where: Prisma.MaterialsInProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.MaterialsInProjectUpdateWithoutMaterialInput, Prisma.MaterialsInProjectUncheckedUpdateWithoutMaterialInput>
}

export type MaterialsInProjectUpdateManyWithWhereWithoutMaterialInput = {
  where: Prisma.MaterialsInProjectScalarWhereInput
  data: Prisma.XOR<Prisma.MaterialsInProjectUpdateManyMutationInput, Prisma.MaterialsInProjectUncheckedUpdateManyWithoutMaterialInput>
}

export type MaterialsInProjectCreateManyProjectInput = {
  id?: string
  materialId: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
}

export type MaterialsInProjectUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  material?: Prisma.MaterialUpdateOneRequiredWithoutProjectUsageNestedInput
}

export type MaterialsInProjectUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialsInProjectUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialsInProjectCreateManyMaterialInput = {
  id?: string
  projectId: string
  quantityUsed: number
  date?: Date | string
  createdAt?: Date | string
}

export type MaterialsInProjectUpdateWithoutMaterialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutMaterialsUsedNestedInput
}

export type MaterialsInProjectUncheckedUpdateWithoutMaterialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialsInProjectUncheckedUpdateManyWithoutMaterialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  quantityUsed?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MaterialsInProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  materialId?: boolean
  quantityUsed?: boolean
  date?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
}, ExtArgs["result"]["materialsInProject"]>

export type MaterialsInProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  materialId?: boolean
  quantityUsed?: boolean
  date?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
}, ExtArgs["result"]["materialsInProject"]>

export type MaterialsInProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  materialId?: boolean
  quantityUsed?: boolean
  date?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
}, ExtArgs["result"]["materialsInProject"]>

export type MaterialsInProjectSelectScalar = {
  id?: boolean
  projectId?: boolean
  materialId?: boolean
  quantityUsed?: boolean
  date?: boolean
  createdAt?: boolean
}

export type MaterialsInProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "materialId" | "quantityUsed" | "date" | "createdAt", ExtArgs["result"]["materialsInProject"]>
export type MaterialsInProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
}
export type MaterialsInProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
}
export type MaterialsInProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
}

export type $MaterialsInProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MaterialsInProject"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    material: Prisma.$MaterialPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    materialId: string
    quantityUsed: number
    date: Date
    createdAt: Date
  }, ExtArgs["result"]["materialsInProject"]>
  composites: {}
}

export type MaterialsInProjectGetPayload<S extends boolean | null | undefined | MaterialsInProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload, S>

export type MaterialsInProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaterialsInProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaterialsInProjectCountAggregateInputType | true
  }

export interface MaterialsInProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MaterialsInProject'], meta: { name: 'MaterialsInProject' } }
  /**
   * Find zero or one MaterialsInProject that matches the filter.
   * @param {MaterialsInProjectFindUniqueArgs} args - Arguments to find a MaterialsInProject
   * @example
   * // Get one MaterialsInProject
   * const materialsInProject = await prisma.materialsInProject.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaterialsInProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MaterialsInProject that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaterialsInProjectFindUniqueOrThrowArgs} args - Arguments to find a MaterialsInProject
   * @example
   * // Get one MaterialsInProject
   * const materialsInProject = await prisma.materialsInProject.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaterialsInProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaterialsInProject that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsInProjectFindFirstArgs} args - Arguments to find a MaterialsInProject
   * @example
   * // Get one MaterialsInProject
   * const materialsInProject = await prisma.materialsInProject.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaterialsInProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, MaterialsInProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaterialsInProject that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsInProjectFindFirstOrThrowArgs} args - Arguments to find a MaterialsInProject
   * @example
   * // Get one MaterialsInProject
   * const materialsInProject = await prisma.materialsInProject.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaterialsInProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaterialsInProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MaterialsInProjects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsInProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MaterialsInProjects
   * const materialsInProjects = await prisma.materialsInProject.findMany()
   * 
   * // Get first 10 MaterialsInProjects
   * const materialsInProjects = await prisma.materialsInProject.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const materialsInProjectWithIdOnly = await prisma.materialsInProject.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MaterialsInProjectFindManyArgs>(args?: Prisma.SelectSubset<T, MaterialsInProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MaterialsInProject.
   * @param {MaterialsInProjectCreateArgs} args - Arguments to create a MaterialsInProject.
   * @example
   * // Create one MaterialsInProject
   * const MaterialsInProject = await prisma.materialsInProject.create({
   *   data: {
   *     // ... data to create a MaterialsInProject
   *   }
   * })
   * 
   */
  create<T extends MaterialsInProjectCreateArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectCreateArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MaterialsInProjects.
   * @param {MaterialsInProjectCreateManyArgs} args - Arguments to create many MaterialsInProjects.
   * @example
   * // Create many MaterialsInProjects
   * const materialsInProject = await prisma.materialsInProject.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaterialsInProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, MaterialsInProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MaterialsInProjects and returns the data saved in the database.
   * @param {MaterialsInProjectCreateManyAndReturnArgs} args - Arguments to create many MaterialsInProjects.
   * @example
   * // Create many MaterialsInProjects
   * const materialsInProject = await prisma.materialsInProject.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MaterialsInProjects and only return the `id`
   * const materialsInProjectWithIdOnly = await prisma.materialsInProject.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MaterialsInProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MaterialsInProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MaterialsInProject.
   * @param {MaterialsInProjectDeleteArgs} args - Arguments to delete one MaterialsInProject.
   * @example
   * // Delete one MaterialsInProject
   * const MaterialsInProject = await prisma.materialsInProject.delete({
   *   where: {
   *     // ... filter to delete one MaterialsInProject
   *   }
   * })
   * 
   */
  delete<T extends MaterialsInProjectDeleteArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MaterialsInProject.
   * @param {MaterialsInProjectUpdateArgs} args - Arguments to update one MaterialsInProject.
   * @example
   * // Update one MaterialsInProject
   * const materialsInProject = await prisma.materialsInProject.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaterialsInProjectUpdateArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MaterialsInProjects.
   * @param {MaterialsInProjectDeleteManyArgs} args - Arguments to filter MaterialsInProjects to delete.
   * @example
   * // Delete a few MaterialsInProjects
   * const { count } = await prisma.materialsInProject.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaterialsInProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaterialsInProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaterialsInProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsInProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MaterialsInProjects
   * const materialsInProject = await prisma.materialsInProject.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaterialsInProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaterialsInProjects and returns the data updated in the database.
   * @param {MaterialsInProjectUpdateManyAndReturnArgs} args - Arguments to update many MaterialsInProjects.
   * @example
   * // Update many MaterialsInProjects
   * const materialsInProject = await prisma.materialsInProject.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MaterialsInProjects and only return the `id`
   * const materialsInProjectWithIdOnly = await prisma.materialsInProject.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MaterialsInProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MaterialsInProject.
   * @param {MaterialsInProjectUpsertArgs} args - Arguments to update or create a MaterialsInProject.
   * @example
   * // Update or create a MaterialsInProject
   * const materialsInProject = await prisma.materialsInProject.upsert({
   *   create: {
   *     // ... data to create a MaterialsInProject
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MaterialsInProject we want to update
   *   }
   * })
   */
  upsert<T extends MaterialsInProjectUpsertArgs>(args: Prisma.SelectSubset<T, MaterialsInProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__MaterialsInProjectClient<runtime.Types.Result.GetResult<Prisma.$MaterialsInProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MaterialsInProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsInProjectCountArgs} args - Arguments to filter MaterialsInProjects to count.
   * @example
   * // Count the number of MaterialsInProjects
   * const count = await prisma.materialsInProject.count({
   *   where: {
   *     // ... the filter for the MaterialsInProjects we want to count
   *   }
   * })
  **/
  count<T extends MaterialsInProjectCountArgs>(
    args?: Prisma.Subset<T, MaterialsInProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaterialsInProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MaterialsInProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsInProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaterialsInProjectAggregateArgs>(args: Prisma.Subset<T, MaterialsInProjectAggregateArgs>): Prisma.PrismaPromise<GetMaterialsInProjectAggregateType<T>>

  /**
   * Group by MaterialsInProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsInProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaterialsInProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaterialsInProjectGroupByArgs['orderBy'] }
      : { orderBy?: MaterialsInProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaterialsInProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaterialsInProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MaterialsInProject model
 */
readonly fields: MaterialsInProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MaterialsInProject.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaterialsInProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  material<T extends Prisma.MaterialDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MaterialDefaultArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MaterialsInProject model
 */
export interface MaterialsInProjectFieldRefs {
  readonly id: Prisma.FieldRef<"MaterialsInProject", 'String'>
  readonly projectId: Prisma.FieldRef<"MaterialsInProject", 'String'>
  readonly materialId: Prisma.FieldRef<"MaterialsInProject", 'String'>
  readonly quantityUsed: Prisma.FieldRef<"MaterialsInProject", 'Int'>
  readonly date: Prisma.FieldRef<"MaterialsInProject", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"MaterialsInProject", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MaterialsInProject findUnique
 */
export type MaterialsInProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * Filter, which MaterialsInProject to fetch.
   */
  where: Prisma.MaterialsInProjectWhereUniqueInput
}

/**
 * MaterialsInProject findUniqueOrThrow
 */
export type MaterialsInProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * Filter, which MaterialsInProject to fetch.
   */
  where: Prisma.MaterialsInProjectWhereUniqueInput
}

/**
 * MaterialsInProject findFirst
 */
export type MaterialsInProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * Filter, which MaterialsInProject to fetch.
   */
  where?: Prisma.MaterialsInProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialsInProjects to fetch.
   */
  orderBy?: Prisma.MaterialsInProjectOrderByWithRelationInput | Prisma.MaterialsInProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaterialsInProjects.
   */
  cursor?: Prisma.MaterialsInProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialsInProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialsInProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaterialsInProjects.
   */
  distinct?: Prisma.MaterialsInProjectScalarFieldEnum | Prisma.MaterialsInProjectScalarFieldEnum[]
}

/**
 * MaterialsInProject findFirstOrThrow
 */
export type MaterialsInProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * Filter, which MaterialsInProject to fetch.
   */
  where?: Prisma.MaterialsInProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialsInProjects to fetch.
   */
  orderBy?: Prisma.MaterialsInProjectOrderByWithRelationInput | Prisma.MaterialsInProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaterialsInProjects.
   */
  cursor?: Prisma.MaterialsInProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialsInProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialsInProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaterialsInProjects.
   */
  distinct?: Prisma.MaterialsInProjectScalarFieldEnum | Prisma.MaterialsInProjectScalarFieldEnum[]
}

/**
 * MaterialsInProject findMany
 */
export type MaterialsInProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * Filter, which MaterialsInProjects to fetch.
   */
  where?: Prisma.MaterialsInProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaterialsInProjects to fetch.
   */
  orderBy?: Prisma.MaterialsInProjectOrderByWithRelationInput | Prisma.MaterialsInProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MaterialsInProjects.
   */
  cursor?: Prisma.MaterialsInProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaterialsInProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaterialsInProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaterialsInProjects.
   */
  distinct?: Prisma.MaterialsInProjectScalarFieldEnum | Prisma.MaterialsInProjectScalarFieldEnum[]
}

/**
 * MaterialsInProject create
 */
export type MaterialsInProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a MaterialsInProject.
   */
  data: Prisma.XOR<Prisma.MaterialsInProjectCreateInput, Prisma.MaterialsInProjectUncheckedCreateInput>
}

/**
 * MaterialsInProject createMany
 */
export type MaterialsInProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MaterialsInProjects.
   */
  data: Prisma.MaterialsInProjectCreateManyInput | Prisma.MaterialsInProjectCreateManyInput[]
}

/**
 * MaterialsInProject createManyAndReturn
 */
export type MaterialsInProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * The data used to create many MaterialsInProjects.
   */
  data: Prisma.MaterialsInProjectCreateManyInput | Prisma.MaterialsInProjectCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MaterialsInProject update
 */
export type MaterialsInProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a MaterialsInProject.
   */
  data: Prisma.XOR<Prisma.MaterialsInProjectUpdateInput, Prisma.MaterialsInProjectUncheckedUpdateInput>
  /**
   * Choose, which MaterialsInProject to update.
   */
  where: Prisma.MaterialsInProjectWhereUniqueInput
}

/**
 * MaterialsInProject updateMany
 */
export type MaterialsInProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MaterialsInProjects.
   */
  data: Prisma.XOR<Prisma.MaterialsInProjectUpdateManyMutationInput, Prisma.MaterialsInProjectUncheckedUpdateManyInput>
  /**
   * Filter which MaterialsInProjects to update
   */
  where?: Prisma.MaterialsInProjectWhereInput
  /**
   * Limit how many MaterialsInProjects to update.
   */
  limit?: number
}

/**
 * MaterialsInProject updateManyAndReturn
 */
export type MaterialsInProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * The data used to update MaterialsInProjects.
   */
  data: Prisma.XOR<Prisma.MaterialsInProjectUpdateManyMutationInput, Prisma.MaterialsInProjectUncheckedUpdateManyInput>
  /**
   * Filter which MaterialsInProjects to update
   */
  where?: Prisma.MaterialsInProjectWhereInput
  /**
   * Limit how many MaterialsInProjects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MaterialsInProject upsert
 */
export type MaterialsInProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the MaterialsInProject to update in case it exists.
   */
  where: Prisma.MaterialsInProjectWhereUniqueInput
  /**
   * In case the MaterialsInProject found by the `where` argument doesn't exist, create a new MaterialsInProject with this data.
   */
  create: Prisma.XOR<Prisma.MaterialsInProjectCreateInput, Prisma.MaterialsInProjectUncheckedCreateInput>
  /**
   * In case the MaterialsInProject was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaterialsInProjectUpdateInput, Prisma.MaterialsInProjectUncheckedUpdateInput>
}

/**
 * MaterialsInProject delete
 */
export type MaterialsInProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
  /**
   * Filter which MaterialsInProject to delete.
   */
  where: Prisma.MaterialsInProjectWhereUniqueInput
}

/**
 * MaterialsInProject deleteMany
 */
export type MaterialsInProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaterialsInProjects to delete
   */
  where?: Prisma.MaterialsInProjectWhereInput
  /**
   * Limit how many MaterialsInProjects to delete.
   */
  limit?: number
}

/**
 * MaterialsInProject without action
 */
export type MaterialsInProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsInProject
   */
  select?: Prisma.MaterialsInProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaterialsInProject
   */
  omit?: Prisma.MaterialsInProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInProjectInclude<ExtArgs> | null
}
